name: Cypress Integration Test Action
description: A composite action to prepare and run an app-specific suite of Cypress tests.

inputs:
  INTEGRATION_APP_PATTERN:
    description: The chosen app/product that will be tested.
    default: src/applications/
    required: true
  CONTAINER_IMAGE:
    description: The container image used to run Cypress.
    default: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/cypress-io/cypress/browsers:node16.16.0-chrome107-ff107-edge
    required: false

runs:
  using: "composite"
  steps:
     
    - name: Login to Amazon ECR
      id: login-ecr    
      uses: aws-actions/amazon-ecr-login@v2    
      with:
        mask-password: false

    - name: Start server
      run: |
        cd vets-website
        python3 -m http.server 3001

    - name: Run Cypress tests
      run: yarn cy:run --browser chrome --headless --spec "$INTEGRATION_APP_PATH"  
      container:
        image: ${{ CONTAINER_IMAGE }}
        credentials:
          username: ${{ ECR_USER }}
          password: ${{ ECR_PASSWORD }}


  
