name: Cypress Integration Test Action
description: A composite action to prepare and run an app-specific suite of Cypress tests.

inputs:
  BUILDTYPE:
    description: The build type for the application.
    default: vagovprod
    required: true
  INTEGRATION_APP_PATTERN:
    description: The chosen app/product that will be tested.
    default: 
    required: true
  CONTAINER_IMAGE:
    description: The container image used to run Cypress.
    default: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/cypress-io/cypress/browsers:node16.16.0-chrome107-ff107-edge
    required: false
  ECR_USER:
    description: ECR user secret
    default:
    required: true
  ECR_PASSWORD:
    description: ECR user secret
    default:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
     
    - name: Login to Amazon ECR
      id: login-ecr    
      uses: aws-actions/amazon-ecr-login@v2    
      with:
        mask-password: false

    - name: Start server
      run: node src/platform/testing/e2e/test-server.js --buildtype=vagovprod --port=3001 &

    - name: Run Cypress tests
      run: yarn cy:run --browser chrome --headless --spec "$INTEGRATION_APP_PATH"  
      container:
        image: ${{ CONTAINER_IMAGE }}
        credentials:
          username: ${{ ECR_USER }}
          password: ${{ ECR_PASSWORD }}


  
