name: Cypress Integration Test Action
description: A composite action to prepare and run an app-specific suite of Cypress tests.

inputs:
  INTEGRATION_APP_PATTERN:
    description: The chosen app/product that will be tested.
    default: src/applications/
    required: true

runs:
  using: "composite"
  steps:

    - name: Start server
      shell: bash
      run: |
        cd vets-website
        python3 -m http.server 3001 &

    - name: Run Cypress tests
      shell: bash
      run: yarn cy:run --browser chrome --headless --spec "$INTEGRATION_APP_PATH"  



  
