name: Cypress Integration Test Action
description: A composite action to prepare and run an app-specific suite of Cypress tests.

inputs:
  INTEGRATION_APP_PATTERN:
    description: The chosen app/product that will be tested.
    default: src/applications/
    required: true
  ECR_USERNAME:
    description: ECR username
    default:
    required: true
  ECR_PASSWORD:
    description: ECR password
    default:
    required: true

runs:
  using: "composite"
  steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.0
      with:
        aws-region: us-gov-west-1
          role-to-assume: arn:aws-us-gov:iam::008577686731:role/gha-frontend-nonprod-role
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2    
      with:
        mask-password: false

    - name: Install dependencies
      uses: ./.github/workflows/install
      with:
        key: ${{ hashFiles('yarn.lock') }}
        yarn_cache_folder: .cache/yarn
        path: |
          .cache/yarn
          node_modules

    - name: Start server
      shell: bash
      run: |
        yarn watch &
        sleep 6s

    - name: Run Cypress tests
      shell: bash
      run: |
        yarn cy:run --headless --spec "$INTEGRATION_APP_PATTERN/**/*.cypress.spec.js"  



  
