name: Cypress Integration Test Action
description: A composite action to prepare and run an app-specific suite of Cypress tests.

inputs:
  INTEGRATION_APP_PATTERN:
    description: The chosen app/product that will be tested.
    default: src/applications/
    required: true

runs:
  using: "composite"
  steps:

    - name: Install dependencies
      uses: ./.github/workflows/install
      with:
        key: ${{ hashFiles('yarn.lock') }}
        yarn_cache_folder: .cache/yarn
        path: |
          .cache/yarn
          node_modules

    - name: Install server dependencies
      shell: bash
      working-directory: vets-website
      run: |
        yarn install

    - name: Start server
      shell: bash
      run: |
        mkdir build
        node src/platform/testing/e2e/test-server.js --buildtype=../vets-website --port=3001 &
    - name: Run Cypress tests
      shell: bash
      run: |
        npx cypress run --config-file config/cypress.config.js --browser chrome --headless --spec '${{INTEGRATION_APP_PATTERN}}/**/*.cypress.spec.js'
