name: Cypress Integration Test Action
description: A composite action to prepare and run an app-specific suite of Cypress tests.

inputs:
  INTEGRATION_APP_PATTERN:
    description: The chosen app/product that will be tested.
    default: src/applications/
    required: true

runs:
  using: "composite"
  steps:
    
    - name: Start server
      shell: bash
      working-directory: vets-website
      run: |
        ls
        python3 -m http.server 3001 &
        sleep 6s

    - name: Run Cypress tests
      shell: bash
      run: |
        export CYPRESS_INSTALL_BINARY=13.13.2
        npx cypress install
        npx cypress run --config-file config/cypress.config.js --browser chrome --headless --spec '$INTEGRATION_APP_PATTERN/**/*.cypress.spec.js'



  
