name: Cypress Integration Test Action
description: A composite action to prepare and run an app-specific suite of Cypress tests.

inputs:
  INTEGRATION_APP_PATTERN:
    description: The chosen app/product that will be tested.
    default: src/applications/
    required: true

runs:
  using: "composite"
  steps:
    
#    - name: Start server
#      shell: bash
#      working-directory: vets-website
#      run: |
#        ls
#        python3 -m http.server 3001 &
#        sleep 6s
#        curl http://localhost:3001/

    - name: Install dependencies
      uses: ./.github/workflows/install
      with:
        key: ${{ hashFiles('yarn.lock') }}
        yarn_cache_folder: .cache/yarn
        path: |
          .cache/yarn
          node_modules
          
#    - name: Run cypres install
#      shell: bash
#      run: |
#        npx cypress install

    - name: Run Cypress tests
      shell: bash
      run: |
        python3 -m http.server 3001 &
        sleep 6s
        curl http://localhost:3001
        curl http://localhost:3001/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez
        curl http://localhost:3001/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez/introduction
        npx cypress run --config-file config/cypress.config.js --browser chrome --headless --spec 'src/applications/burials-ez/**/*.cypress.spec.js'
