name: Holiday Checker
description: A GitHub Action that checks if today is a holiday and outputs a true/false result.
outputs:
  is_holiday:
    description: 'True if today is a holiday, otherwise False'
    value: ${{ steps.holiday-check.outputs.is_holiday }}
inputs:
  holidays:
    description: 'List of Holidays in YYYY-MM-DD format'
    default: >
      2025-01-01
      2025-01-02
      2025-01-03
      2025-01-09
runs:
  using: 'composite'
  steps:
    - name: Is Today a Holiday
      id: holiday-check
      shell: bash
      run: |
        TODAY=$(TZ='America/New_York' date +"%Y-%m-%d")
        DATES=(${{ inputs.holidays }})
        IS_HOLIDAY="false"

        for date in "${DATES[@]}"
        do
          if [[ "${date}" == "${TODAY}" ]]
          then
            IS_HOLIDAY="true"
            break
          fi
        done

        echo "is_holiday=${IS_HOLIDAY}" >> $GITHUB_OUTPUT

        if [[ "${IS_HOLIDAY}" == "true" ]]
        then
          echo "Today (${TODAY}, Eastern Time Zone) is a holiday."
        else
          echo "Today (${TODAY}, Eastern Time Zone) is not a holiday."
        fi
