name: Holiday Checker
description: A GitHub Action that checks if today is a holiday and outputs a true/false result.
outputs:
  is_holiday:
    description: 'True if today is a holiday, otherwise False'
    value: ${{ steps.holiday-check.outputs.is_holiday }}
inputs:
  holidays:
    description: 'List of Holidays in YYYY-MM-DD format'
    default: >
      2026-01-01
      2026-01-02
      2026-01-03
      2026-01-04
      2026-01-19
      2026-05-25
      2026-06-19
      2026-07-03
      2026-07-04
      2026-09-07
      2026-11-11
      2026-11-26
      2026-11-27
      2026-12-21
      2026-12-22
      2026-12-23
      2026-12-24
      2026-12-25
      2026-12-26
      2026-12-27
      2026-12-28
      2026-12-29
      2026-12-30
      2026-12-31
      2027-01-01
      2027-01-02
      2027-01-03

runs:
  using: 'composite'
  steps:
    - name: Is Today a Holiday
      id: holiday-check
      shell: bash
      run: |
        TODAY=$(TZ='America/New_York' date +"%Y-%m-%d")
        DATES=(${{ inputs.holidays }})
        IS_HOLIDAY="false"

        for date in "${DATES[@]}"
        do
          if [[ "${date}" == "${TODAY}" ]]
          then
            IS_HOLIDAY="true"
            break
          fi
        done

        echo "is_holiday=${IS_HOLIDAY}" >> $GITHUB_OUTPUT

        if [[ "${IS_HOLIDAY}" == "true" ]]
        then
          echo "Today (${TODAY}, Eastern Time Zone) is a holiday."
        else
          echo "Today (${TODAY}, Eastern Time Zone) is not a holiday."
        fi
