name: Freeze Day Checker
description: A GitHub Action that checks if today is a freeze day and outputs a true/false result.
outputs:
  is_holiday:
    description: 'True if today is a freeze day, otherwise False'
    value: ${{ steps.freeze-check.outputs.is_freeze }}
inputs:
  freeze_days:
    description: 'List of Freeze Days in YYYY-MM-DD format'
    default: >
      2025-01-01
      2025-01-02
      2025-01-03
      2025-01-09
      2025-01-20
      2025-05-26
      2025-06-19
      2025-07-04
      2025-09-01
      2025-10-02
      2025-10-03
      2025-10-04
      2025-10-05
      2025-10-06
      2025-10-07
      2025-10-08
      2025-10-09
      2025-10-10
      2025-10-11
      2025-10-12
      2025-10-13
      2025-10-14
      2025-10-15
      2025-10-16
      2025-10-17
      2025-10-18
      2025-10-19
      2025-10-20
      2025-10-21
      2025-10-22
      2025-10-23
      2025-10-24
      2025-10-25
      2025-10-26
      2025-10-27
      2025-10-28
      2025-10-29
      2025-10-30
      2025-10-31
      2025-11-11
      2025-11-27
      2025-11-28
      2025-12-22
      2025-12-23
      2025-12-24
      2025-12-25
      2025-12-27
      2025-12-28
      2025-12-29
      2025-12-30
      2025-12-31
      2026-01-01
      2026-01-02
      2026-01-03
      2026-01-04

runs:
  using: 'composite'
  steps:
    - name: Is Today a Freeze Day
      id: freeze-check
      shell: bash
      run: |
        TODAY=$(TZ='America/New_York' date +"%Y-%m-%d")
        DATES=(${{ inputs.freeze_days }})
        IS_FREEZE="false"

        for date in "${DATES[@]}"
        do
          if [[ "${date}" == "${TODAY}" ]]
          then
            IS_FREEZE="true"
            break
          fi
        done

        echo "is_freeze=${IS_FREEZE}" >> $GITHUB_OUTPUT

        if [[ "${IS_FREEZE}" == "true" ]]
        then
          echo "Today (${TODAY}, Eastern Time Zone) is a freeze day."
        else
          echo "Today (${TODAY}, Eastern Time Zone) is not a freeze day."
        fi
