name: AMI Image SBOM Generation

on:
  workflow_call:
    inputs:
      output_bucket:
        type: string
        required: true
        default: "whoops"
      artifact_identifier:
        type: string
        required:   true
        default: "whoops"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-gov-west-1
        role-to-assume: ${{ vars.AWS_ASSUME_ROLE }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      continue-on-error: true
      with:
        input: '${{ inputs.artifact_identifier }}'
        format: 'cyclonedx'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        output: "${{ inputs.artifact_identifier }}.json"
        list-all-pkgs: true


      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@0.20.0
      #   continue-on-error: true
      #   with:
      #     image-ref: '${{ steps.get_id.outputs.ami_id }}'
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Convert to one line JSON
      run: >- 
        cat ${{ inputs.artifact_identifier }}.json 
        | tr -d \\n 
        | tr -d " " > 
        ${{ inputs.artifact_identifier }}.single.json 
    - name: Copy SBOM to Bucket
      run: >- 
        aws s3 cp 
        "${{ inputs.artifact_identifier }}.single.json" 
        ${{ inputs.output_bucket }}
