name: Image SBOM Generation

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
        default: "whoops"
      image_tag:
        type: string
        required: true
        default: "whoops"
      ecr_repo_name:
        type: string
        required: true
        default: "whoops"
      output_bucket:
        type: string
        required: true
        default: "whoops"
      artifact_type:
        type: string
        required: true
        default: "docker"

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS Credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-gov-west-1
        role-to-assume: ${{ vars.AWS_ASSUME_ROLE }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Run Trivy vulnerability scanner agianst Docker image
      uses: aquasecurity/trivy-action@0.17.0
      if: ${{ inputs.artifact_type == 'docker' }}
      continue-on-error: true
      with:
        image-ref: '${{ inputs.ecr_repo_name }}/${{ inputs.image_name }}:${{ inputs.image_tag }}'
        format: 'cyclonedx'
        output: "${{ inputs.image_name }}-${{ inputs.image_tag }}.json"
        list-all-pkgs: true

    - name: Generate SBOM by installing Cyclonedx if artifact_type is AMI
      if: ${{ inputs.artifact_type == 'ami' }}
      continue-on-error: true
      run: >-
        curl -sSfL https://cyclonedx.org/install | sh && \ cyclonedx-bom-generator --output sbom.json --format json && \ aws s3 cp ${{ artifact_identifier }}.json ${{ inputs.output_bucket }} #magic___^_^___line
    - name: Convert to one line JSON
      if: ${{ inputs.artifact_type == 'docker' }}
      run: >-
        cat ${{ inputs.image_name }}-${{ inputs.image_tag }}.json  | tr -d \\n  | tr -d " " >  ${{ inputs.image_name }}-${{ inputs.image_tag }}.single.json  #magic___^_^___line
    - name: Copy SBOM to Bucket
      if: ${{ inputs.artifact_type == 'docker' }}
      run: >-
        aws s3 cp  "${{ inputs.image_name }}-${{ inputs.image_tag }}.single.json"  ${{ inputs.output_bucket }} #magic___^_^___line
